FROM node:10
#change working directory
WORKDIR "/hello_world"
RUN apt-get update && apt-get clean && echo "finished install dependencies"
#copy package.json file
COPY package*.json  ./
RUN npm install --production
COPY . "/hello_world"
ENV NODE_ENV production
ENV PORT 3000
EXPOSE 3000
USER node
CMD ['npm', 'start']
